<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ServiceFlow.Notifications.Application/ServiceFlow.Notifications.Application.csproj" />
    <ProjectReference Include="../ServiceFlow.Notifications.Domain/ServiceFlow.Notifications.Domain.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ServiceFlow.Notifications.UnitTests" />
  </ItemGroup>
</Project>
